### PR TITLE
Add `initial_input` to `MarketBidCost`

### PR DESCRIPTION
**Pull request by GabrielKS**
Quick and dirty implementation, very much a draft at the moment — I'm not super happy with the now greater asymmetry of this interface (see https://github.com/NREL-Sienna/PowerSystems.jl/issues/1150). Also I haven't done decremental yet — I'll do that once we finalize an interface — and the docs and tests are incomplete. But it is something functional to test with.

Minor potential violation of SemVer: the old `MarketBidCost` flavor, which lacks an `initial_input`, still exists, but its `initial_input` is now set to `nothing` rather than `NaN`. This change probably should have been made as soon as we made `initial_input` nullable.

### CODE REVIEW

**Comment by kdayday** [comment]
@jd-lara @pesap is there any timeline on this pull request review? Currently we have a failing market bid example in the documentation, but I'm waiting to update if changes are going to happen soon. Thanks!

**Comment by pesap** [comment]
> @jd-lara @pesap is there any timeline on this pull request review? Currently we have a failing market bid example in the documentation, but I'm waiting to update if changes are going to happen soon. Thanks!

I think @rodrigomha is working on this.

**Comment by rodrigomha** [comment]
We should close #1187 with this PR

**Review by rodrigomha — CHANGES_REQUESTED** [review]
There is an issue related with promotion of Int to Float in no_load_cost that should promote:

```
Got exception outside of a @test
  MethodError: Cannot `convert` an object of type 
    Int64 to an object of type 
    Union{Float64, TimeSeriesKey}
  
  Closest candidates are:
    convert(::Type{T}, !Matched::T) where T
     @ Base Base.jl:84
  
  Stacktrace:
    [1] convert(::Type{Union{Nothing, Float64, TimeSeriesKey}}, x::Int64)
      @ Base ./some.jl:37
    [2] MarketBidCost(no_load_cost::Int64, start_up::@NamedTuple{hot::Float64, warm::Float64, cold::Float64}, shut_down::Float64, incremental_offer_curves::CostCurve{PiecewiseIncrementalCurve}, decremental_offer_curves::Nothing, incremental_initial_input::Nothing, ancillary_service_offers::Vector{Service})
```

**Comment by rodrigomha** [comment]
Proposed interface ready for review. Requires https://github.com/NREL-Sienna/PowerSystemCaseBuilder.jl/pull/109 and https://github.com/NREL-Sienna/PowerSystemsTestData/pull/63

**Comment by jd-lara** [comment]
@rodrigomha the change in https://github.com/NREL-Sienna/PowerSystems.jl/pull/1151/commits/ee432111bdc3113adb7caa9c8e3424e4fc0c0d73 fixes the backwards compatibility broken by this PR

**Review by jd-lara — APPROVED** [review]
If the tests pass we should merge

**Comment by kdayday** [comment]
> We should close #1187 with this PR

@rodrigomha  can you check whether #1187 is closed?

**Pull request merged**
