### PR TITLE
Fixing the failed test

### PR DESCRIPTION
**Pull request by tengis-nrl**
tests_passing_subsystems
Thanks for opening a PR to PowerSystems.jl, please take note of the following when making a PR:

Check the [contributor guidelines](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/developer/)

1. Add a description of the changes proposed in the pull request.
2. Is my PR fixing an open issue? Add the reference to the related issue
3. If you are contributing a new struct: please refer to the [testing requirements for new structs](https://nrel-sienna.github.io/PowerSystems.jl/stable/code_base_developer_guide/adding_new_types/#Testing-the-addition-of-new-struct-to-the-code-base)

### CODE REVIEW

**Review by GabrielKS — CHANGES_REQUESTED** [review]
Screenshot 2024-02-20 at 3 12 41 PM
This is still failing for me when I (merge with `psb4` locally to get the changes since these branches diverged and then) run the full test suite with `pkg> test`. It also fails when I `TestEnv.activate()` and then step through the test in the REPL.

**Comment by GabrielKS** [comment]
My guess is the issue is that you are relying on a list of components from `get_components` to be sorted in a particular way when you do `get_name(components[14])`; I don't think this is something that `get_components` guarantees.

**Comment by tengis-nrl** [comment]
Does it give you the same error @GabrielKS?

**Comment by tengis-nrl** [comment]
@GabrielKS Try now. I replaced the index access with get_component

**Review by GabrielKS — APPROVED** [review]
Screenshot 2024-02-20 at 4 27 56 PM

Now it works for me

**Pull request merged**
